name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [21, 22, 23, 24]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxss-dev libinput-dev libudev-dev

    - name: Add user to input group
      if: runner.os == 'Linux'
      run: sudo usermod -a -G input $USER

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run test on Linux
      if: runner.os == 'Linux'
      run: sg input -c "npm test"

    - name: Run test on Windows and macOS
      if: runner.os != 'Linux'
      run: npm test
